import { describe, expect, it } from "vitest";
import {
  getCardImagePath,
  getCardThumbnailPath,
  MAJOR_ARCANA,
  TAROT_CARDS,
} from "../apps/miniprogram/core/cards";
import { MINOR_ARCANA } from "../apps/miniprogram/core/minor-cards";
import {
  buildFallbackInterpretation,
  buildStaticDailyInterpretation,
  buildTopicInsight,
  FIXED_DISCLAIMER,
  LOCAL_DISCLAIMER,
  validateInterpretation,
} from "../apps/miniprogram/core/interpretation";
import type { InterpretationContent, Reading } from "../apps/miniprogram/core/types";

const reading: Reading = {
  id: "question-test",
  type: "question",
  spread: "single",
  status: "drawn",
  businessDate: "2026-07-19",
  topic: "self",
  question: "我该如何理解最近的犹豫？",
  cards: [{ cardId: TAROT_CARDS[9].id, orientation: "upright", drawOrder: 1 }],
  saved: false,
  createdAt: "2026-07-19T00:00:00.000Z",
  updatedAt: "2026-07-19T00:00:00.000Z",
};

const validOutput: InterpretationContent = {
  summary: "隐士提示你暂时离开外界噪音，区分真实需要与急于得到答案的焦虑，再决定下一步。",
  cards: [{
    cardId: "major-09",
    cardName: "隐士",
    orientation: "upright",
    position: "focus",
    positionLabel: "核心牌",
    basis: TAROT_CARDS[9].upright,
    contextualMeaning: "把安静观察作为整理犹豫的方法，而不是逃避行动。",
    topicLabel: "自我",
    topicInsight: "从减少噪音开始，辨认真正需要和外界期待。",
  }],
  synthesis: "隐士提供的是一个观察角度，把牌义放回真实处境，再决定最值得验证的一项。",
  reflectionQuestion: "减少一种外界声音后，你自己的判断是什么？",
  microAction: "今天留出十分钟，只记录事实和自己的感受。",
  disclaimer: FIXED_DISCLAIMER,
};

describe("validateInterpretation", () => {
  it("defines a complete ordered 78-card deck", () => {
    const minorRanks = [
      "ace",
      "two",
      "three",
      "four",
      "five",
      "six",
      "seven",
      "eight",
      "nine",
      "ten",
      "page",
      "knight",
      "queen",
      "king",
    ];
    expect(TAROT_CARDS).toHaveLength(78);
    expect(MAJOR_ARCANA).toHaveLength(22);
    expect(MINOR_ARCANA).toHaveLength(56);
    expect(MAJOR_ARCANA.every((card) => card.arcana === "major")).toBe(true);
    expect(MINOR_ARCANA.every((card) => card.arcana === "minor")).toBe(true);
    expect(TAROT_CARDS.map((card) => card.sequence)).toEqual(
      Array.from({ length: 78 }, (_, index) => index),
    );
    expect(new Set(TAROT_CARDS.map((card) => card.id)).size).toBe(78);
    for (const suit of ["wands", "cups", "swords", "pentacles"] as const) {
      const suitCards = MINOR_ARCANA.filter((card) => card.suit === suit);
      expect(suitCards).toHaveLength(14);
      expect(suitCards.map((card) => card.rank)).toEqual(minorRanks);
    }
  });

  it("provides focused topic insights and unique image mappings for all 78 cards", () => {
    const paths = new Set<string>();
    const thumbnailPaths = new Set<string>();
    for (const card of TAROT_CARDS) {
      const relationship = buildTopicInsight(card, "upright", "relationship");
      const career = buildTopicInsight(card, "reversed", "career");
      expect(relationship.topicLabel).toBe("感情");
      expect(career.topicLabel).toBe("事业");
      expect(relationship.topicInsight).not.toBe(career.topicInsight);
      expect(relationship.basis).toBe(card.upright);
      expect(career.basis).toBe(card.reversed);
      const imagePath = getCardImagePath(card.id);
      const thumbnailPath = getCardThumbnailPath(card.id);
      expect(imagePath).toMatch(/^\/packages\/deck\/assets\/cards\/.+\.jpg$/);
      expect(thumbnailPath).toMatch(/^\/assets\/card-thumbs\/.+\.jpg$/);
      paths.add(imagePath);
      thumbnailPaths.add(thumbnailPath);
    }
    expect(paths.size).toBe(78);
    expect(thumbnailPaths.size).toBe(78);
  });

  it("accepts output that matches the reading facts", () => {
    expect(validateInterpretation(validOutput, reading)).toEqual({ valid: true, content: validOutput });
  });

  it("accepts a new reading without a manually selected topic", () => {
    const generalReading = { ...reading, topic: undefined };
    const generalOutput = {
      ...validOutput,
      cards: [{ ...validOutput.cards[0], topicLabel: "你的问题" }],
    };
    expect(validateInterpretation(generalOutput, generalReading)).toEqual({ valid: true, content: generalOutput });
  });

  it("labels local daily and fallback content without claiming it was generated by AI", () => {
    const dailyReading = { ...reading, type: "daily" as const };
    expect(buildStaticDailyInterpretation(dailyReading, TAROT_CARDS[9]).disclaimer).toBe(LOCAL_DISCLAIMER);
    expect(buildFallbackInterpretation(reading, [TAROT_CARDS[9]], "AI_TIMEOUT").disclaimer).toBe(LOCAL_DISCLAIMER);
  });

  it("rejects a different card or orientation", () => {
    const invalid = { ...validOutput, cards: [{ ...validOutput.cards[0], orientation: "reversed" as const }] };
    expect(validateInterpretation(invalid, reading)).toEqual({ valid: false, reasonCode: "CARD_FACT_MISMATCH" });
  });

  it("rejects a mismatched spread position", () => {
    const invalid = { ...validOutput, cards: [{ ...validOutput.cards[0], position: "situation" as const }] };
    expect(validateInterpretation(invalid, reading)).toEqual({ valid: false, reasonCode: "CARD_FACT_MISMATCH" });
  });

  it("rejects an insight labeled for a different topic", () => {
    const invalid = { ...validOutput, cards: [{ ...validOutput.cards[0], topicLabel: "事业" }] };
    expect(validateInterpretation(invalid, reading)).toEqual({ valid: false, reasonCode: "TOPIC_MISMATCH" });
  });

  it("rejects the old all-dimensions payload when focused topic insight is missing", () => {
    const { topicLabel: _topicLabel, topicInsight: _topicInsight, ...legacyCard } = validOutput.cards[0];
    const invalid = { ...validOutput, cards: [{ ...legacyCard, loveInsight: "旧版爱情字段" }] };
    expect(validateInterpretation(invalid, reading)).toEqual({ valid: false, reasonCode: "INVALID_CARD_CONTENT" });
  });

  it("rejects unsafe deterministic language", () => {
    const invalid = { ...validOutput, summary: "这个结果百分百准确，你必须分手，然后一切都会好起来。" };
    expect(validateInterpretation(invalid, reading)).toEqual({ valid: false, reasonCode: "UNSAFE_OUTPUT" });
  });

  it("rejects a summary that mechanically repeats the user's question", () => {
    const invalid = {
      ...validOutput,
      summary: `关于你提到的“${reading.question}”，隐士建议你先停下来观察。`,
    };
    expect(validateInterpretation(invalid, reading)).toEqual({
      valid: false,
      reasonCode: "SUMMARY_REPEATS_QUESTION",
    });
  });
});
