import type { TarotCard } from "./types";

export const MINOR_ARCANA: TarotCard[] = [
  {
    id: "minor-wands-ace", sequence: 22, roman: "A", name: "权杖王牌", englishName: "Ace of Wands",
    arcana: "minor", suit: "wands", rank: "ace", keywords: ["灵感", "潜能", "启动"],
    upright: "新的热情或创造冲动正在出现，先用一个具体动作验证它是否值得继续投入。",
    reversed: "能量可能被压住、分散或过早耗尽，需要缩小起点并辨认真正想做的事。",
    reflection: "哪一个想法让你有行动冲动，又能在今天小范围试一试？",
  },
  {
    id: "minor-wands-02", sequence: 23, roman: "II", name: "权杖二", englishName: "Two of Wands",
    arcana: "minor", suit: "wands", rank: "two", keywords: ["规划", "视野", "选择"],
    upright: "你已经站在可选择的位置，扩大视野并比较代价，会让下一步更有方向。",
    reversed: "对未知的顾虑或准备不足可能缩小选择，先补齐最关键的信息而非停在想象中。",
    reflection: "如果把眼光放远一点，哪个选择更符合你真正想建设的方向？",
  },
  {
    id: "minor-wands-03", sequence: 24, roman: "III", name: "权杖三", englishName: "Three of Wands",
    arcana: "minor", suit: "wands", rank: "three", keywords: ["拓展", "进展", "远见"],
    upright: "前期投入开始向外延伸，适合观察反馈、连接资源并为下一阶段预留空间。",
    reversed: "进展可能受阻于估计偏差或协作脱节，需要回看计划与现实之间的距离。",
    reflection: "已有哪一点进展值得继续放大，又有哪些假设需要重新核实？",
  },
  {
    id: "minor-wands-04", sequence: 25, roman: "IV", name: "权杖四", englishName: "Four of Wands",
    arcana: "minor", suit: "wands", rank: "four", keywords: ["庆祝", "稳定", "归属"],
    upright: "一个阶段性的稳定值得确认和庆祝，可靠的关系与空间也在提供支持。",
    reversed: "表面的和谐可能尚未落稳，或你难以允许自己享受成果，需要先处理基础裂缝。",
    reflection: "什么成果值得被认真承认，什么基础还需要再加固一点？",
  },
  {
    id: "minor-wands-05", sequence: 26, roman: "V", name: "权杖五", englishName: "Five of Wands",
    arcana: "minor", suit: "wands", rank: "five", keywords: ["竞争", "摩擦", "磨合"],
    upright: "不同意见和力量正在碰撞，这既会消耗，也可能暴露需要磨合的真实差异。",
    reversed: "冲突可能被回避、内化或无休止重复，需要区分有价值的讨论与徒劳较劲。",
    reflection: "这场摩擦里，哪一个分歧值得说清，哪一种争胜可以停下？",
  },
  {
    id: "minor-wands-06", sequence: 27, roman: "VI", name: "权杖六", englishName: "Six of Wands",
    arcana: "minor", suit: "wands", rank: "six", keywords: ["认可", "进展", "信心"],
    upright: "努力更容易被看见，接受合理认可并总结有效方法，可以把信心变成持续进展。",
    reversed: "对认可的依赖或暂时未被看见，可能动摇判断，需要回到可验证的成果本身。",
    reflection: "抛开掌声或冷落，什么具体证据说明你确实向前了一步？",
  },
  {
    id: "minor-wands-07", sequence: 28, roman: "VII", name: "权杖七", englishName: "Seven of Wands",
    arcana: "minor", suit: "wands", rank: "seven", keywords: ["立场", "边界", "坚持"],
    upright: "你需要为重要立场守住边界，在压力中集中保护真正不能让步的部分。",
    reversed: "持续防御可能让人疲惫，或你正因压力放弃立场，需要重新评估战线与资源。",
    reflection: "此刻最值得守住的一条边界是什么，哪些次要战线可以放下？",
  },
  {
    id: "minor-wands-08", sequence: 29, roman: "VIII", name: "权杖八", englishName: "Eight of Wands",
    arcana: "minor", suit: "wands", rank: "eight", keywords: ["速度", "讯息", "推进"],
    upright: "信息与行动正在快速汇聚，清楚回应和减少阻塞能让事情顺势推进。",
    reversed: "延误、误传或同时推进过多事项可能打乱节奏，需要重新排序并确认信息。",
    reflection: "哪一条消息或行动如果现在处理，会解除最大的等待？",
  },
  {
    id: "minor-wands-09", sequence: 30, roman: "IX", name: "权杖九", englishName: "Nine of Wands",
    arcana: "minor", suit: "wands", rank: "nine", keywords: ["韧性", "警觉", "保留"],
    upright: "经历消耗后仍有继续的力量，但坚持需要更聪明的边界和恢复，而非硬撑。",
    reversed: "过度警觉或疲惫可能让你把所有变化都当成威胁，也可能已接近资源极限。",
    reflection: "为了继续走下去，你最需要保护、补充或停止的是什么？",
  },
  {
    id: "minor-wands-10", sequence: 31, roman: "X", name: "权杖十", englishName: "Ten of Wands",
    arcana: "minor", suit: "wands", rank: "ten", keywords: ["负担", "责任", "过载"],
    upright: "责任已经接近承载上限，完成固然重要，也需要重新分配、简化或请求支持。",
    reversed: "你可能正在卸下负担，也可能因不愿放手而继续独自承担不属于自己的部分。",
    reflection: "哪一项责任可以委托、延期、缩小，或直接归还给真正的负责人？",
  },
  {
    id: "minor-wands-page", sequence: 32, roman: "PAGE", name: "权杖侍从", englishName: "Page of Wands",
    arcana: "minor", suit: "wands", rank: "page", keywords: ["好奇", "讯号", "探索"],
    upright: "新鲜讯号唤起探索欲，适合带着初学者心态试验，而不必先拥有完整答案。",
    reversed: "兴奋可能停在口号，或害怕显得生疏而不敢开始，需要把热情落到小任务。",
    reflection: "如果允许自己只是探索，你最想先接近哪个新方向？",
  },
  {
    id: "minor-wands-knight", sequence: 33, roman: "KNIGHT", name: "权杖骑士", englishName: "Knight of Wands",
    arcana: "minor", suit: "wands", rank: "knight", keywords: ["追逐", "热情", "冒进"],
    upright: "强烈动力适合突破停滞，但速度越快越要确认方向、承诺和可承受的风险。",
    reversed: "冲动、反复转向或只追求刺激，可能让行动失去后续，需要先稳住节奏。",
    reflection: "怎样保留这股热情，同时给它加上一条必要的现实护栏？",
  },
  {
    id: "minor-wands-queen", sequence: 34, roman: "QUEEN", name: "权杖王后", englishName: "Queen of Wands",
    arcana: "minor", suit: "wands", rank: "queen", keywords: ["自信", "创造", "感染力"],
    upright: "稳定的自信与创造力能带动周围，不必缩小自己，也无需压过别人的光。",
    reversed: "比较、自我怀疑或过度维持强势形象，可能遮住真正需要与可用能力。",
    reflection: "当你不再和别人比较，哪一种能力最值得大方地使用？",
  },
  {
    id: "minor-wands-king", sequence: 35, roman: "KING", name: "权杖国王", englishName: "King of Wands",
    arcana: "minor", suit: "wands", rank: "king", keywords: ["愿景", "领导", "影响"],
    upright: "清楚愿景与承担能力可以聚拢行动，领导意味着让方向落地并为影响负责。",
    reversed: "急躁掌控、夸大承诺或只靠个人意志推进，可能消耗信任与执行质量。",
    reflection: "你希望带领事情去哪里，又愿意为这个方向承担什么具体责任？",
  },

  {
    id: "minor-cups-ace", sequence: 36, roman: "A", name: "圣杯王牌", englishName: "Ace of Cups",
    arcana: "minor", suit: "cups", rank: "ace", keywords: ["情感", "开放", "连接"],
    upright: "新的感受、善意或连接正在涌现，允许情绪流动，同时用真实互动承接它。",
    reversed: "情感可能被压抑、外溢或投注在无法承接之处，需要先照顾自己的容器。",
    reflection: "哪一种感受需要被诚实承认，而不是立刻解释或压下去？",
  },
  {
    id: "minor-cups-02", sequence: 37, roman: "II", name: "圣杯二", englishName: "Two of Cups",
    arcana: "minor", suit: "cups", rank: "two", keywords: ["互惠", "连接", "共识"],
    upright: "平等回应与真诚交换正在形成连接，关系的质量来自双方自愿和边界清楚。",
    reversed: "误解、不对等或内外需求失衡可能削弱连接，需要把期待直接摆到桌面。",
    reflection: "这段连接里，双方真正同意了什么，又有哪些期待仍只是猜测？",
  },
  {
    id: "minor-cups-03", sequence: 38, roman: "III", name: "圣杯三", englishName: "Three of Cups",
    arcana: "minor", suit: "cups", rank: "three", keywords: ["友谊", "庆祝", "支持"],
    upright: "共同庆祝与同伴支持能放大喜悦，也提醒你让成果被关系网络真实承接。",
    reversed: "社交过载、圈层摩擦或表面热闹，可能掩盖边界和真实连接的问题。",
    reflection: "谁能真诚分享你的喜悦，又有哪些社交消耗可以减少？",
  },
  {
    id: "minor-cups-04", sequence: 39, roman: "IV", name: "圣杯四", englishName: "Four of Cups",
    arcana: "minor", suit: "cups", rank: "four", keywords: ["倦怠", "停顿", "重估"],
    upright: "熟悉的选项暂时失去吸引力，停下来辨认真实需要，比勉强接受更有价值。",
    reversed: "你可能开始重新看见机会，也可能因不耐烦而抓住第一个出口，需要先确认动机。",
    reflection: "你是在拒绝不适合的东西，还是因疲惫错过了值得重新看的可能？",
  },
  {
    id: "minor-cups-05", sequence: 40, roman: "V", name: "圣杯五", englishName: "Five of Cups",
    arcana: "minor", suit: "cups", rank: "five", keywords: ["失落", "哀伤", "余留"],
    upright: "失落值得被看见，但并非所有资源都已消失；哀伤之后再回看仍被保留的部分。",
    reversed: "你可能正在走出失落，或仍反复停在无法改变之处，需要允许恢复有自己的速度。",
    reflection: "承认已经失去的同时，还有什么关系、能力或选择仍然在你身边？",
  },
  {
    id: "minor-cups-06", sequence: 41, roman: "VI", name: "圣杯六", englishName: "Six of Cups",
    arcana: "minor", suit: "cups", rank: "six", keywords: ["记忆", "纯真", "过去"],
    upright: "过去的温暖经验正在提供线索，可以带回真诚与善意，但不必复刻旧日。",
    reversed: "怀旧、美化过去或旧模式回返，可能让你忽略现在已经改变的条件。",
    reflection: "过去有什么值得带回当下，又有什么只适合被温柔地留在过去？",
  },
  {
    id: "minor-cups-07", sequence: 42, roman: "VII", name: "圣杯七", englishName: "Seven of Cups",
    arcana: "minor", suit: "cups", rank: "seven", keywords: ["选择", "想象", "辨别"],
    upright: "可能性很多却真假混杂，先核实条件、代价和优先级，再让想象进入行动。",
    reversed: "迷雾可能正在散去，或你因害怕选错而过早封闭选择，需要回到可验证信息。",
    reflection: "这些选项中，哪一个有事实支撑，哪一个主要依赖愿望或恐惧？",
  },
  {
    id: "minor-cups-08", sequence: 43, roman: "VIII", name: "圣杯八", englishName: "Eight of Cups",
    arcana: "minor", suit: "cups", rank: "eight", keywords: ["离开", "寻找", "取舍"],
    upright: "某些投入已无法回应更深需要，离开熟悉并不轻松，却可能是诚实的选择。",
    reversed: "对离开的犹豫、反复返回或逃避未处理的问题，可能让转身失去方向。",
    reflection: "你想离开的是已经完成的阶段，还是一段尚未被认真面对的困难？",
  },
  {
    id: "minor-cups-09", sequence: 44, roman: "IX", name: "圣杯九", englishName: "Nine of Cups",
    arcana: "minor", suit: "cups", rank: "nine", keywords: ["满足", "享受", "感恩"],
    upright: "愿望获得部分满足，允许自己享受成果，同时辨认满足是否真实而可持续。",
    reversed: "外在拥有可能没有填补内在需要，或短期享乐正在替代更重要的建设。",
    reflection: "什么是真正让你充实的满足，什么只是暂时转移注意力？",
  },
  {
    id: "minor-cups-10", sequence: 45, roman: "X", name: "圣杯十", englishName: "Ten of Cups",
    arcana: "minor", suit: "cups", rank: "ten", keywords: ["归属", "和谐", "共享"],
    upright: "共同价值和情感安全感正在形成，值得通过真实参与维护，而不只停在理想画面。",
    reversed: "家庭或群体的完美想象可能遮住分歧，需要允许真实关系不完全符合模板。",
    reflection: "你想要的归属由哪些具体互动构成，而不是由怎样的完美画面构成？",
  },
  {
    id: "minor-cups-page", sequence: 46, roman: "PAGE", name: "圣杯侍从", englishName: "Page of Cups",
    arcana: "minor", suit: "cups", rank: "page", keywords: ["敏感", "讯息", "想象"],
    upright: "细腻感受或意外讯息打开想象，保持柔软的同时，也要给情绪找到表达方式。",
    reversed: "情绪化、逃入幻想或害怕表达脆弱，可能让真实需要变得更难被听见。",
    reflection: "如果不担心显得幼稚，你最想诚实表达哪一种感受？",
  },
  {
    id: "minor-cups-knight", sequence: 47, roman: "KNIGHT", name: "圣杯骑士", englishName: "Knight of Cups",
    arcana: "minor", suit: "cups", rank: "knight", keywords: ["理想", "邀请", "追寻"],
    upright: "理想与情感推动你靠近重要事物，真诚表达需要同时接受现实回应与边界。",
    reversed: "浪漫化、情绪起伏或只爱想象中的结果，可能让承诺与现实脱节。",
    reflection: "这个愿望如何转成尊重现实、也尊重他人选择的一步？",
  },
  {
    id: "minor-cups-queen", sequence: 48, roman: "QUEEN", name: "圣杯王后", englishName: "Queen of Cups",
    arcana: "minor", suit: "cups", rank: "queen", keywords: ["共情", "直觉", "承接"],
    upright: "深度感受与共情能承接复杂情绪，但理解别人不等于替别人承担。",
    reversed: "情绪边界模糊、过度吸收他人感受或忽略自身需要，可能造成内在耗竭。",
    reflection: "哪些感受属于你，哪些是你正在替别人背负的？",
  },
  {
    id: "minor-cups-king", sequence: 49, roman: "KING", name: "圣杯国王", englishName: "King of Cups",
    arcana: "minor", suit: "cups", rank: "king", keywords: ["成熟", "稳定", "关怀"],
    upright: "情绪成熟不是没有波动，而是在波动中仍能关怀、沟通并承担自己的选择。",
    reversed: "压抑、操纵情绪或用冷静形象回避感受，可能削弱信任与自我理解。",
    reflection: "怎样既承认真实情绪，又不让它替你决定全部行动？",
  },

  {
    id: "minor-swords-ace", sequence: 50, roman: "A", name: "宝剑王牌", englishName: "Ace of Swords",
    arcana: "minor", suit: "swords", rank: "ace", keywords: ["清晰", "事实", "决断"],
    upright: "关键事实或清晰判断正在浮现，适合把问题说准，并据此作出可解释的决定。",
    reversed: "信息混乱、表达失准或过早定论可能制造新的误解，需要先核实核心事实。",
    reflection: "如果只能保留一条可核实事实，它会如何改变你的判断？",
  },
  {
    id: "minor-swords-02", sequence: 51, roman: "II", name: "宝剑二", englishName: "Two of Swords",
    arcana: "minor", suit: "swords", rank: "two", keywords: ["僵持", "保护", "选择"],
    upright: "暂时僵持可能是在保护自己，也提示决定不能无限延后；先明确真正缺少的信息。",
    reversed: "压住冲突已难以维持，信息过载或逃避选择可能让焦虑继续增加。",
    reflection: "你是在等待必要信息，还是在等待一个无需承担代价的选择？",
  },
  {
    id: "minor-swords-03", sequence: 52, roman: "III", name: "宝剑三", englishName: "Three of Swords",
    arcana: "minor", suit: "swords", rank: "three", keywords: ["伤痛", "分离", "真相"],
    upright: "令人难受的事实或分离需要被承认，清楚命名伤痛是修复的开始而非失败。",
    reversed: "伤口可能正在愈合，也可能因回避或反复触碰而延长，需要为恢复创造边界。",
    reflection: "这份痛苦要求你承认什么事实，又需要怎样的保护来慢慢恢复？",
  },
  {
    id: "minor-swords-04", sequence: 53, roman: "IV", name: "宝剑四", englishName: "Four of Swords",
    arcana: "minor", suit: "swords", rank: "four", keywords: ["休息", "恢复", "整合"],
    upright: "暂停输入与行动有助于恢复和整合，休息是下一步判断的条件而非浪费。",
    reversed: "长期停滞、无法真正休息或过早重返压力，可能让消耗以另一种方式继续。",
    reflection: "哪一种休息能真正减少负荷，而不是让你带着焦虑继续刷动信息？",
  },
  {
    id: "minor-swords-05", sequence: 54, roman: "V", name: "宝剑五", englishName: "Five of Swords",
    arcana: "minor", suit: "swords", rank: "five", keywords: ["冲突", "胜负", "代价"],
    upright: "赢下一场争执不等于解决问题，先看清胜负背后的关系、信任与长期代价。",
    reversed: "你可能愿意结束消耗，也可能仍在暗中延续冲突，需要明确修复或退出方式。",
    reflection: "即使证明自己是对的，你可能失去什么；有没有代价更低的处理方式？",
  },
  {
    id: "minor-swords-06", sequence: 55, roman: "VI", name: "宝剑六", englishName: "Six of Swords",
    arcana: "minor", suit: "swords", rank: "six", keywords: ["过渡", "离开", "迁移"],
    upright: "你正离开较混乱的状态，过渡未必轻松，但稳定移动比立即抵达更重要。",
    reversed: "旧问题被带入新环境或转变受阻，提示你需要处理尚未完成的部分。",
    reflection: "为了真正进入下一阶段，哪一件旧事需要先被安置或说清？",
  },
  {
    id: "minor-swords-07", sequence: 56, roman: "VII", name: "宝剑七", englishName: "Seven of Swords",
    arcana: "minor", suit: "swords", rank: "seven", keywords: ["策略", "隐瞒", "独行"],
    upright: "策略和独立行动可能必要，但信息隐藏也会带来信任与责任上的代价。",
    reversed: "隐瞒可能暴露，或你准备停止自我欺骗；坦诚仍需选择合适边界与时机。",
    reflection: "你是在保护必要隐私、采用策略，还是在逃避应承担的诚实与后果？",
  },
  {
    id: "minor-swords-08", sequence: 57, roman: "VIII", name: "宝剑八", englishName: "Eight of Swords",
    arcana: "minor", suit: "swords", rank: "eight", keywords: ["限制", "信念", "视角"],
    upright: "限制感部分来自现实，部分来自尚未检验的假设；区分二者会出现新的缝隙。",
    reversed: "你可能开始看见出口，也可能因熟悉的恐惧而不敢尝试，需要用小证据松动束缚。",
    reflection: "哪些限制是客观条件，哪些只是你还没有验证过的推断？",
  },
  {
    id: "minor-swords-09", sequence: 58, roman: "IX", name: "宝剑九", englishName: "Nine of Swords",
    arcana: "minor", suit: "swords", rank: "nine", keywords: ["焦虑", "反刍", "恐惧"],
    upright: "担忧在独处时被放大，先把事实与最坏想象分开，并为自己寻找现实支持。",
    reversed: "焦虑可能正在缓解，或因羞耻而更隐蔽；持续影响生活时应寻求可靠帮助。",
    reflection: "你最害怕的解释有哪些证据支持，又有哪些证据并不支持？",
  },
  {
    id: "minor-swords-10", sequence: 59, roman: "X", name: "宝剑十", englishName: "Ten of Swords",
    arcana: "minor", suit: "swords", rank: "ten", keywords: ["终点", "崩解", "释放"],
    upright: "一个痛苦阶段已经到达无法继续维持的终点，承认结束能停止额外消耗。",
    reversed: "最坏阶段可能正在过去，也可能因拒绝结束而被延长，需要把恢复拆成小步。",
    reflection: "什么已经明确结束，停止继续证明或挽回后，你能把力气用在哪里？",
  },
  {
    id: "minor-swords-page", sequence: 60, roman: "PAGE", name: "宝剑侍从", englishName: "Page of Swords",
    arcana: "minor", suit: "swords", rank: "page", keywords: ["警觉", "提问", "表达"],
    upright: "好奇与敏锐适合调查、提问和学习，但观点越锋利越需要核实与负责地表达。",
    reversed: "流言、过度警觉或未经验证就发言，可能把聪明变成噪音与误伤。",
    reflection: "在表达判断之前，你还应该确认哪一个来源或向谁直接提问？",
  },
  {
    id: "minor-swords-knight", sequence: 61, roman: "KNIGHT", name: "宝剑骑士", englishName: "Knight of Swords",
    arcana: "minor", suit: "swords", rank: "knight", keywords: ["直进", "速度", "交锋"],
    upright: "清晰目标推动快速行动，直接可以穿透拖延，也要留意语气、风险与遗漏信息。",
    reversed: "急于证明、言语攻击或方向不明的冲刺，可能造成比问题更大的破坏。",
    reflection: "这件事真的需要更快，还是需要先多听一句、多核实一步？",
  },
  {
    id: "minor-swords-queen", sequence: 62, roman: "QUEEN", name: "宝剑王后", englishName: "Queen of Swords",
    arcana: "minor", suit: "swords", rank: "queen", keywords: ["辨别", "独立", "坦率"],
    upright: "经验带来清楚辨别与坦率边界，可以保持同理，但不必用模糊换取表面和平。",
    reversed: "刻薄、防御或把过去伤痛当成唯一判断标准，可能让清晰变成隔绝。",
    reflection: "怎样把真正需要说清的话表达得直接，同时不把伤害当成力量？",
  },
  {
    id: "minor-swords-king", sequence: 63, roman: "KING", name: "宝剑国王", englishName: "King of Swords",
    arcana: "minor", suit: "swords", rank: "king", keywords: ["理性", "原则", "权责"],
    upright: "以事实、原则和长远后果作判断，权威的价值在于透明标准与可被检验。",
    reversed: "冷酷操控、滥用规则或只用逻辑压过经验，可能让决定失去正当性。",
    reflection: "如果你的判断需要向所有受影响的人解释，依据是否足够清楚和公平？",
  },

  {
    id: "minor-pentacles-ace", sequence: 64, roman: "A", name: "星币王牌", englishName: "Ace of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "ace", keywords: ["机会", "基础", "资源"],
    upright: "一个现实机会或资源种子正在出现，价值取决于你是否建立可持续的承接方式。",
    reversed: "机会可能准备不足、代价被低估或只停在物质想象，需要先核算基础条件。",
    reflection: "要让这个机会真正落地，第一项必须准备好的现实条件是什么？",
  },
  {
    id: "minor-pentacles-02", sequence: 65, roman: "II", name: "星币二", englishName: "Two of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "two", keywords: ["平衡", "适应", "优先级"],
    upright: "多项责任需要动态协调，保持弹性有用，但必须知道哪个优先级不能被牺牲。",
    reversed: "安排过载或频繁切换正在侵蚀质量，需要减少并行任务并重新分配资源。",
    reflection: "如果只能稳定做好两件事，你会留下什么，又会暂停什么？",
  },
  {
    id: "minor-pentacles-03", sequence: 66, roman: "III", name: "星币三", englishName: "Three of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "three", keywords: ["协作", "技艺", "标准"],
    upright: "专业分工、反馈与共同标准能让成果超过单打独斗，适合把过程变得可协作。",
    reversed: "角色不清、标准不一或不愿听取专业意见，可能让投入无法组合成质量。",
    reflection: "这个成果还需要哪一种不同能力，以及怎样的共同标准来完成？",
  },
  {
    id: "minor-pentacles-04", sequence: 67, roman: "IV", name: "星币四", englishName: "Four of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "four", keywords: ["安全", "控制", "执着"],
    upright: "保护资源和边界能带来稳定，也要留意过度抓紧是否阻止必要流动与信任。",
    reversed: "你可能正在松开控制，也可能因缺乏边界而流失资源，需要重新定义安全感。",
    reflection: "你抓紧的是必要保障，还是一种已经妨碍成长的控制？",
  },
  {
    id: "minor-pentacles-05", sequence: 68, roman: "V", name: "星币五", englishName: "Five of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "five", keywords: ["匮乏", "排除", "援助"],
    upright: "资源压力或被排除感值得正视，但支持可能比你当前看见的更近，求助不是失败。",
    reversed: "处境可能开始改善，或羞耻仍阻止你使用支持，需要把恢复落实到具体资源。",
    reflection: "你现在真正缺少的是什么，谁或哪项制度可能提供实际帮助？",
  },
  {
    id: "minor-pentacles-06", sequence: 69, roman: "VI", name: "星币六", englishName: "Six of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "six", keywords: ["给予", "接受", "权力"],
    upright: "资源交换需要慷慨也需要公平，留意给予者与接受者之间的条件、尊严和权力。",
    reversed: "附带控制的帮助、不平等交换或拒绝接受支持，可能让资源关系继续失衡。",
    reflection: "这次给予或接受是否尊重双方选择，并把条件说得足够清楚？",
  },
  {
    id: "minor-pentacles-07", sequence: 70, roman: "VII", name: "星币七", englishName: "Seven of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "seven", keywords: ["耐心", "评估", "培育"],
    upright: "长期投入需要耐心复盘，先看真实生长与机会成本，再决定继续、调整或停止。",
    reversed: "急于看到回报、投入方式低效或沉没成本，可能让坚持变成重复消耗。",
    reflection: "哪些进展证明值得继续培育，哪些信号说明方法需要改变？",
  },
  {
    id: "minor-pentacles-08", sequence: 71, roman: "VIII", name: "星币八", englishName: "Eight of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "eight", keywords: ["练习", "精进", "专注"],
    upright: "稳定练习与细节改进正在累积能力，把注意力放在可重复的高质量动作上。",
    reversed: "机械重复、完美主义或不愿打磨基础，可能让忙碌无法转化为真正成长。",
    reflection: "哪一个基础动作如果重复做好，会最明显地提高整体质量？",
  },
  {
    id: "minor-pentacles-09", sequence: 72, roman: "IX", name: "星币九", englishName: "Nine of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "nine", keywords: ["独立", "成果", "品味"],
    upright: "独立积累带来更从容的选择，享受成果的同时，也看见背后长期维护的能力。",
    reversed: "表面体面可能依赖过度消耗，或你难以认可自己的成果，需要核对真实基础。",
    reflection: "你已经建立了哪一种不依赖外界认可也能站稳的能力？",
  },
  {
    id: "minor-pentacles-10", sequence: 73, roman: "X", name: "星币十", englishName: "Ten of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "ten", keywords: ["传承", "稳定", "体系"],
    upright: "长期结构、共同资源和经验传承正在形成，稳定来自系统而非一次好运。",
    reversed: "家庭或组织资源分配失衡、短视安排或旧规则，可能削弱长期安全。",
    reflection: "你正在建设的东西，怎样才能在没有你亲自盯住时仍然持续？",
  },
  {
    id: "minor-pentacles-page", sequence: 74, roman: "PAGE", name: "星币侍从", englishName: "Page of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "page", keywords: ["学习", "计划", "实践"],
    upright: "务实学习和新计划值得投入，从基础技能与可衡量步骤开始会更可靠。",
    reversed: "拖延基础、目标飘忽或只收集知识不实践，可能让机会停留在准备阶段。",
    reflection: "要靠近这个目标，你今天能完成哪一个可检查的学习或准备动作？",
  },
  {
    id: "minor-pentacles-knight", sequence: 75, roman: "KNIGHT", name: "星币骑士", englishName: "Knight of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "knight", keywords: ["勤勉", "规律", "可靠"],
    upright: "稳定、重复和责任感正在建立可靠结果，速度不快不等于没有进展。",
    reversed: "僵化惯性、枯燥耗竭或只守流程不看目标，可能让稳定变成停滞。",
    reflection: "哪一项规律值得继续，哪一项只是因为习惯而没有真正产生价值？",
  },
  {
    id: "minor-pentacles-queen", sequence: 76, roman: "QUEEN", name: "星币王后", englishName: "Queen of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "queen", keywords: ["照料", "资源", "踏实"],
    upright: "现实照料、资源安排与温度可以并存，先把生活基础安顿好，再支持更远目标。",
    reversed: "过度照料别人、忽略身体与财务边界，可能让可靠变成长期透支。",
    reflection: "你怎样照顾现实基础，才能既支持别人也不牺牲自己的稳定？",
  },
  {
    id: "minor-pentacles-king", sequence: 77, roman: "KING", name: "星币国王", englishName: "King of Pentacles",
    arcana: "minor", suit: "pentacles", rank: "king", keywords: ["经营", "丰盛", "责任"],
    upright: "成熟经营把资源转化为长期稳定，真正的丰盛也包含责任、边界与可持续分配。",
    reversed: "对物质或地位的执着、资源控制或短视逐利，可能损害更重要的长期基础。",
    reflection: "你希望拥有怎样的稳定，又愿意用什么原则管理它带来的资源与权力？",
  },
];
